# Generated by Django 4.1.5 on 2023-01-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admins', models.CharField(max_length=50, verbose_name='User Name')),
            ],
        ),
    ]
