# Generated by Django 4.1.5 on 2023-01-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=50, verbose_name='User Name')),
                ('admin_password', models.CharField(max_length=50, verbose_name='Password')),
            ],
            options={
                'db_table': 'admins',
            },
        ),
    ]
